### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by tcriscuolo**

### CODE REVIEW

**Comment by viniciusvdias** [comment]
Did you removed Travis support? Why's that ?

I just realized that we need to explain better EEmbedding/VEmbedding. I think the most used APIs will be:

ArabesqueResult.embeddings
and
ArabesqueResult.readAggregation

... at least on earlier versions

Also we could add some examples (with the sample data already in the repo) in this API doc.
https://gist.github.com/viniciusvdias/22a3513d3614e30ee3f195246a2931d9

What do you think?

**Comment by viniciusvdias** [comment]
Oh, I see. Yes we should get a department organization on github fast,
right? :/

About the comments, yeah, maybe some minimal configuration for running each
algorithm. The code snippet would be placed also on top of the func
definitions, following the description.
Example:

/*
* FSM computes ....... blah blah
*
* You can obtain the resulting embedding of FSM through ArabesqueGraph:
* val fsmRes = // config considering datasets in the repository
* val embeddings = // get embeddings
* and also read aggregations (per pattern in this case)
* val perPattern = // read key that contains frequent patterns, etc.
**/
def fsm(...)

I am pretty sure that there is a specific syntax for code in scala docs.
May be good to take a look.

We would repeat that for all current algorithms.

**Comment by tcriscuolo** [comment]
Just to make sure,

Is that definition for vertex induced embedding right ?

/**
  * A vertex induced embedding
  * 
  * Current semantics: Array(a, b, c, d) returns the 
  * embedding induced by the vertices {a, b, c, d} 
  *
  * @param words integer array indicating the embedding vertices
  */
case class VEmbedding(var words: Array[Int]) extends ResultEmbedding {
  ....
}

**Comment by carloshct** [comment]
yes.

**Comment by tcriscuolo** [comment]
I've added some description of how to use some arabesque graph computation, the scaladoc is looking 
like this


screenshot from 2016-07-13 13 32 41

**Comment by viniciusvdias** [comment]
That's perfect! Thank you Tulio.
Better than what I had in mind.

**Pull request merged**
